//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProphetLamb.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProphetLamb.Tools.ExceptionResource", typeof(ExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array must conatin at least one element..
        /// </summary>
        internal static string ARRAY_NOTEMPTY {
            get {
                return ResourceManager.GetString("ARRAY_NOTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumerable has to enumerate at least one element..
        /// </summary>
        internal static string ENUMERABLE_NOTEMPTY {
            get {
                return ResourceManager.GetString("ENUMERABLE_NOTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index was greater or equal to the length of the array..
        /// </summary>
        internal static string INDEX_UPPERLIMIT {
            get {
                return ResourceManager.GetString("INDEX_UPPERLIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a nonnegative integer..
        /// </summary>
        internal static string INTEGER_POSITIVEZERO {
            get {
                return ResourceManager.GetString("INTEGER_POSITIVEZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null or whitespace..
        /// </summary>
        internal static string STRING_NULLWHITESPACE {
            get {
                return ResourceManager.GetString("STRING_NULLWHITESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null or empty..
        /// </summary>
        internal static string STRING_NULLEMPTY {
            get {
                return ResourceManager.GetString("STRING_NULLEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list must contain at least one element..
        /// </summary>
        internal static string LIST_NOTEMPTY {
            get {
                return ResourceManager.GetString("LIST_NOTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value must be smaller or equal to the end value..
        /// </summary>
        internal static string RANGE_STARTEND_SMALLEREQUALS {
            get {
                return ResourceManager.GetString("RANGE_STARTEND_SMALLEREQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null..
        /// </summary>
        internal static string VALUE_NOTNULL {
            get {
                return ResourceManager.GetString("VALUE_NOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary can not be a ConcurrentDictionary..
        /// </summary>
        internal static string DICTIONARY_CONCURRENT_NOTSUPPORTED {
            get {
                return ResourceManager.GetString("DICTIONARY_CONCURRENT_NOTSUPPORTED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid culture name..
        /// </summary>
        internal static string CULTURE_INVALID {
            get {
                return ResourceManager.GetString("CULTURE_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type does not have at least one generic type argument..
        /// </summary>
        internal static string TYPE_NOTGENERIC {
            get {
                return ResourceManager.GetString("TYPE_NOTGENERIC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The number of elements in the collection do not match the expected value..
        /// </summary>
        internal static string COLLECTION_LENGTH_INVALID {
            get {
                return ResourceManager.GetString("COLLECTION_LENGTH_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file specified does not exisit on the device..
        /// </summary>
        internal static string FILE_NOTONDEVICE {
            get {
                return ResourceManager.GetString("FILE_NOTONDEVICE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A resource set with the same culture already exisits..
        /// </summary>
        internal static string RESOURCESET_CULTURE_EXISTS {
            get {
                return ResourceManager.GetString("RESOURCESET_CULTURE_EXISTS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call ReadToEnd before calling this method..
        /// </summary>
        internal static string RESOURCEREADER_REQUIRE_READTOEND {
            get {
                return ResourceManager.GetString("RESOURCEREADER_REQUIRE_READTOEND", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key is not present in the dictionary..
        /// </summary>
        internal static string RESOURCESET_RESOURCEMISS {
            get {
                return ResourceManager.GetString("RESOURCESET_RESOURCEMISS", resourceCulture);
            }
        }
    }
}
