//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groundbeef.SharedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Groundbeef.SharedResources.ExceptionResource", typeof(ExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alphabet contains less then two characters..
        /// </summary>
        public static string ALPHABET_LENGTH_LESS_2 {
            get {
                return ResourceManager.GetString("ALPHABET_LENGTH_LESS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more element is null..
        /// </summary>
        public static string ANY_ELEMENT_NULL {
            get {
                return ResourceManager.GetString("ANY_ELEMENT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower bound of the array has to be zero..
        /// </summary>
        public static string ARRAY_LOWERBOUND_ZERO {
            get {
                return ResourceManager.GetString("ARRAY_LOWERBOUND_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multirank arrays are not supported..
        /// </summary>
        public static string ARRAY_MULTIRANK_NOTSUPPORTED {
            get {
                return ResourceManager.GetString("ARRAY_MULTIRANK_NOTSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array must conatin at least one element..
        /// </summary>
        public static string ARRAY_NOTEMPTY {
            get {
                return ResourceManager.GetString("ARRAY_NOTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be called by the system assembly..
        /// </summary>
        public static string CALL_FROM_CORE_ASSEMBLY_FAILED {
            get {
                return ResourceManager.GetString("CALL_FROM_CORE_ASSEMBLY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class does not have the attribute required..
        /// </summary>
        public static string CLASS_NOT_HAVE_ATTRIBUTE {
            get {
                return ResourceManager.GetString("CLASS_NOT_HAVE_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type of elements in the array..
        /// </summary>
        public static string COLLECTION_INVALID_ELEMENTTYPE {
            get {
                return ResourceManager.GetString("COLLECTION_INVALID_ELEMENTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements in the collection do not match the expected value..
        /// </summary>
        public static string COLLECTION_LENGTH_INVALID {
            get {
                return ResourceManager.GetString("COLLECTION_LENGTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection cannt be empty..
        /// </summary>
        public static string COLLECTION_NOT_EMPTY {
            get {
                return ResourceManager.GetString("COLLECTION_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match for the predicate was found in the collection..
        /// </summary>
        public static string COLLECTION_PREDICATE_NO_MATCH_FOUND {
            get {
                return ResourceManager.GetString("COLLECTION_PREDICATE_NO_MATCH_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the name of the System assembly..
        /// </summary>
        public static string CORE_ASSEMBY_NAME_INDETERMINABLE {
            get {
                return ResourceManager.GetString("CORE_ASSEMBY_NAME_INDETERMINABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking the constructor method failed..
        /// </summary>
        public static string CTOR_INVOKE_FAILED {
            get {
                return ResourceManager.GetString("CTOR_INVOKE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid culture name..
        /// </summary>
        public static string CULTURE_INVALID {
            get {
                return ResourceManager.GetString("CULTURE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary can not be a ConcurrentDictionary..
        /// </summary>
        public static string DICTIONARY_CONCURRENT_NOTSUPPORTED {
            get {
                return ResourceManager.GetString("DICTIONARY_CONCURRENT_NOTSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumerable has to enumerate at least one element..
        /// </summary>
        public static string ENUMERABLE_NOTEMPTY {
            get {
                return ResourceManager.GetString("ENUMERABLE_NOTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of the enumerator is abnormal..
        /// </summary>
        public static string ENUMERATOR_STATE_ABNORMAL {
            get {
                return ResourceManager.GetString("ENUMERATOR_STATE_ABNORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified does not exisit on the device..
        /// </summary>
        public static string FILE_NOTONDEVICE {
            get {
                return ResourceManager.GetString("FILE_NOTONDEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No known format recognized..
        /// </summary>
        public static string FORMAT_NOT_RECOGNIZED {
            get {
                return ResourceManager.GetString("FORMAT_NOT_RECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index was greater or equal to the length of the array..
        /// </summary>
        public static string INDEX_UPPERLIMIT {
            get {
                return ResourceManager.GetString("INDEX_UPPERLIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a nonnegative integer..
        /// </summary>
        public static string INTEGER_POSITIVEZERO {
            get {
                return ResourceManager.GetString("INTEGER_POSITIVEZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is invalid or does not point to a directory..
        /// </summary>
        public static string INVALID_DIRECTORY_PATH {
            get {
                return ResourceManager.GetString("INVALID_DIRECTORY_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the JObject form the reader..
        /// </summary>
        public static string JOBJECT_READER_LOAD_FAILED {
            get {
                return ResourceManager.GetString("JOBJECT_READER_LOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key specified was not found..
        /// </summary>
        public static string KEY_NOTFOUND {
            get {
                return ResourceManager.GetString("KEY_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list must contain at least one element..
        /// </summary>
        public static string LIST_NOTEMPTY {
            get {
                return ResourceManager.GetString("LIST_NOTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking the method failed..
        /// </summary>
        public static string METHOD_INVOKE_FAILED {
            get {
                return ResourceManager.GetString("METHOD_INVOKE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method does not have the attribute required..
        /// </summary>
        public static string METHOD_NOT_HAVE_ATTRIBUTE {
            get {
                return ResourceManager.GetString("METHOD_NOT_HAVE_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No property with the name specified was found..
        /// </summary>
        public static string PROPERTY_NAME_NOTFOUND {
            get {
                return ResourceManager.GetString("PROPERTY_NAME_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested property cannot be set to the specified value..
        /// </summary>
        public static string PROPERTY_READONLY {
            get {
                return ResourceManager.GetString("PROPERTY_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bounds of the range must be fully assigned..
        /// </summary>
        public static string RANGE_BOUNDS_NOT_ASSIGNED {
            get {
                return ResourceManager.GetString("RANGE_BOUNDS_NOT_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value must be smaller or equal to the end value..
        /// </summary>
        public static string RANGE_STARTEND_SMALLEREQUALS {
            get {
                return ResourceManager.GetString("RANGE_STARTEND_SMALLEREQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting a System.Range to a Range&lt;int&gt; requires Index.IsFromEnd to be false..
        /// </summary>
        public static string RANGE_TO_GENERIC_ISFROMEND {
            get {
                return ResourceManager.GetString("RANGE_TO_GENERIC_ISFROMEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call ReadToEnd before calling this method..
        /// </summary>
        public static string RESOURCEREADER_REQUIRE_READTOEND {
            get {
                return ResourceManager.GetString("RESOURCEREADER_REQUIRE_READTOEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource set with the same culture already exisits..
        /// </summary>
        public static string RESOURCESET_CULTURE_EXISTS {
            get {
                return ResourceManager.GetString("RESOURCESET_CULTURE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key is not present in the dictionary..
        /// </summary>
        public static string RESOURCESET_RESOURCEMISS {
            get {
                return ResourceManager.GetString("RESOURCESET_RESOURCEMISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A provider with this type of store object is already registered..
        /// </summary>
        public static string SETTINGS_PROVIDER_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("SETTINGS_PROVIDER_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No provider with this type of store object exists..
        /// </summary>
        public static string SETTINGS_PROVIDER_NOTFOUND {
            get {
                return ResourceManager.GetString("SETTINGS_PROVIDER_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null or empty..
        /// </summary>
        public static string STRING_NULLEMPTY {
            get {
                return ResourceManager.GetString("STRING_NULLEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null or whitespace..
        /// </summary>
        public static string STRING_NULLWHITESPACE {
            get {
                return ResourceManager.GetString("STRING_NULLWHITESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to the type specified..
        /// </summary>
        public static string TYPE_CANNOT_CONVERT_TO_TYPE {
            get {
                return ResourceManager.GetString("TYPE_CANNOT_CONVERT_TO_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the type of the arguments..
        /// </summary>
        public static string TYPE_INDETERMINABLE {
            get {
                return ResourceManager.GetString("TYPE_INDETERMINABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is no attribute type..
        /// </summary>
        public static string TYPE_ISNOT_ATTRIBUTE {
            get {
                return ResourceManager.GetString("TYPE_ISNOT_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type specified is no interface.
        /// </summary>
        public static string TYPE_ISNOT_INTERFACE {
            get {
                return ResourceManager.GetString("TYPE_ISNOT_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is required to be an enum..
        /// </summary>
        public static string TYPE_MUST_BE_ENUM {
            get {
                return ResourceManager.GetString("TYPE_MUST_BE_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type does implement the generic type definition IEnumerable&lt;&gt;..
        /// </summary>
        public static string TYPE_NOT_IMPLEMENT_GENERIC_IENUMERABLE {
            get {
                return ResourceManager.GetString("TYPE_NOT_IMPLEMENT_GENERIC_IENUMERABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type does not have at least one generic type argument..
        /// </summary>
        public static string TYPE_NOTGENERIC {
            get {
                return ResourceManager.GetString("TYPE_NOTGENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string source contains corrupted unicode symbols, at index {0}.
        /// </summary>
        public static string UNICODE_ILLEGAL_SYMBOL {
            get {
                return ResourceManager.GetString("UNICODE_ILLEGAL_SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null..
        /// </summary>
        public static string VALUE_NOTNULL {
            get {
                return ResourceManager.GetString("VALUE_NOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value can only be set once..
        /// </summary>
        public static string VALUE_ONLY_SET_ONCE {
            get {
                return ResourceManager.GetString("VALUE_ONLY_SET_ONCE", resourceCulture);
            }
        }
    }
}
